spring:
    datasource:
        url: ${jdbc.url}
        username: ${jdbc.username}
        password: ${jdbc.password}
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        #minIdle: 1
        #maxActive: 2
        #initialSize: 1
        #timeBetweenEvictionRunsMillis: 3000
        #minEvictableIdleTimeMillis: 300000
        #validationQuery: SELECT 'ZTM' FROM DUAL
        #testWhileIdle: true
        #testOnBorrow: false
        #testOnReturn: false

    application:
        name: springBootDemo
        instance_id: clent-one
mybatis:
    mapperLocations: classpath*:mapper/*.xml
    typeAliasesPackage: com.springboot.test.domain
springfox:
    api:
        group: group-001
        title: 测试 swagger
        desc: 自动化的在线 api 文档
        version: v2
        termsOfServiceUrl: termsUrl
        contact: jcs7575@gmail.com
        license: licenseSample
        licenseUrl: licenseUrl
#    documentation:
#        swagger:
#            v2:
#                path: apis
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    statusPageUrlPath: ${management.contextPath}/info
#    healthCheckUrlPath: ${management.contextPath}/health
info:
    app:
        name: ecs
        version: 1.0.0

    build:
        artifactId: @project.artifactId@
        version: @project.version@
endpoints:
    shutdown:
        enabled: true
    restart:
        enabled: true
